PRAGMA foreign_keys = ON;

DELETE FROM applications WHERE public_id IN (
  'IND-EV-26-DEMO01', 'IND-EV-26-DEMO02', 'IND-EV-26-DEMO03',
  'IND-EV-26-DEMO04', 'IND-EV-26-DEMO05', 'IND-EV-26-DEMO06'
);

INSERT INTO applications (id, public_id, status, email, nationality, visa_type_id, proposed_arrival, applicant_name, dob, passport_number, sections_json, version, created_at, updated_at, submitted_at, rejection_reason) VALUES
  (1, 'IND-EV-26-DEMO01', 'DRAFT', 'maya.thompson@example.test', 'United States', 'e-tourist', '2026-11-18', 'Maya Thompson', '1996-08-14', 'P1234567', '{"visa":{"nationality":"United States","visaCategory":"Tourism","visaSubtype":"e-tourist","purpose":"Tourism","proposedArrival":"2026-11-18","arrivalPort":"Delhi International Airport"},"personal":{"surname":"Thompson","givenNames":"Maya","gender":"Female","dob":"1996-08-14","birthCity":"Seattle","birthCountry":"United States","citizenship":"United States"},"passport":{"passportNumber":"P1234567","passportType":"Ordinary","issuingCountry":"United States"}}', 3, '2026-08-28T08:10:00.000Z', '2026-08-29T09:15:00.000Z', NULL, NULL),
  (2, 'IND-EV-26-DEMO02', 'PAYMENT_PENDING', 'daniel.weber@example.test', 'Germany', 'e-business', '2026-10-22', 'Daniel Weber', '1988-02-19', 'C01X8831', '{"visa":{"nationality":"Germany","visaCategory":"Business","visaSubtype":"e-business","purpose":"Business meetings","proposedArrival":"2026-10-22","arrivalPort":"Mumbai International Airport"},"personal":{"surname":"Weber","givenNames":"Daniel","gender":"Male","dob":"1988-02-19","birthCity":"Berlin","birthCountry":"Germany","citizenship":"Germany","religion":"Not stated","identificationMarks":"None","education":"University"},"passport":{"passportNumber":"C01X8831","passportType":"Ordinary","issuingCountry":"Germany","placeOfIssue":"Berlin","issueDate":"2019-04-10","expiryDate":"2029-04-09"},"contact":{"address1":"14 Lindenstrasse","city":"Berlin","state":"Berlin","postalCode":"10115","country":"Germany","email":"daniel.weber@example.test","mobile":"+49 30 555 0100"},"family":{"fatherName":"Klaus Weber","fatherNationality":"Germany","motherName":"Anna Weber","motherNationality":"Germany","maritalStatus":"Married"},"employment":{"occupation":"Director","employer":"Weber Handels GmbH","designation":"Managing Director","employerAddress":"14 Lindenstrasse, Berlin","employerPhone":"+49 30 555 0101","industry":"Trade"},"travel":{"expectedArrival":"2026-10-22","expectedDeparture":"2026-10-30","arrivalPort":"Mumbai International Airport","places":"Mumbai and Pune","accommodationName":"Harbour View Hotel","accommodationAddress":"Apollo Bunder, Mumbai","indiaReference":"Ravi Mehta","indiaReferencePhone":"+91 22 5555 0101","homeReferenceName":"Anna Weber","homeReferenceRelationship":"Spouse","homeReferencePhone":"+49 30 555 0102","homeReferenceAddress":"14 Lindenstrasse, Berlin"},"background":{"visaRefusal":"No","deportation":"No","conviction":"No","immigrationViolation":"No","restrictedTravel":"No","declaration":true}}', 7, '2026-08-25T10:00:00.000Z', '2026-08-28T15:20:00.000Z', '2026-08-28T15:20:00.000Z', NULL),
  (3, 'IND-EV-26-DEMO03', 'UNDER_REVIEW', 'sophie.martin@example.test', 'France', 'e-tourist', '2026-10-14', 'Sophie Martin', '1992-11-03', '22FV61948', '{"visa":{"nationality":"France","visaCategory":"Tourism","visaSubtype":"e-tourist","purpose":"Holiday","proposedArrival":"2026-10-14","arrivalPort":"Kochi International Airport"},"personal":{"surname":"Martin","givenNames":"Sophie","gender":"Female","dob":"1992-11-03","birthCity":"Lyon","birthCountry":"France","citizenship":"France","religion":"Not stated","identificationMarks":"None","education":"University"},"passport":{"passportNumber":"22FV61948","passportType":"Ordinary","issuingCountry":"France","placeOfIssue":"Lyon","issueDate":"2020-06-15","expiryDate":"2030-06-14"},"contact":{"address1":"8 Rue des Lilas","city":"Lyon","state":"Auvergne-Rhone-Alpes","postalCode":"69002","country":"France","email":"sophie.martin@example.test","mobile":"+33 4 5555 0100"},"family":{"fatherName":"Jean Martin","fatherNationality":"France","motherName":"Claire Martin","motherNationality":"France","maritalStatus":"Single"},"employment":{"occupation":"Editor","employer":"Maison Culture","designation":"Senior Editor","employerAddress":"2 Place Bellecour, Lyon","employerPhone":"+33 4 5555 0101","industry":"Publishing"},"travel":{"expectedArrival":"2026-10-14","expectedDeparture":"2026-10-28","arrivalPort":"Kochi International Airport","places":"Kochi, Munnar and Goa","accommodationName":"Pepper House Guest Rooms","accommodationAddress":"Fort Kochi, Kerala","indiaReference":"Anita Nair","indiaReferencePhone":"+91 484 555 0101","homeReferenceName":"Jean Martin","homeReferenceRelationship":"Father","homeReferencePhone":"+33 4 5555 0102","homeReferenceAddress":"8 Rue des Lilas, Lyon"},"background":{"visaRefusal":"No","deportation":"No","conviction":"No","immigrationViolation":"No","restrictedTravel":"No","declaration":true}}', 10, '2026-08-20T09:00:00.000Z', '2026-08-27T11:30:00.000Z', '2026-08-26T12:00:00.000Z', NULL),
  (4, 'IND-EV-26-DEMO04', 'DOCUMENT_REUPLOAD_REQUIRED', 'kenji.sato@example.test', 'Japan', 'e-business', '2026-09-28', 'Kenji Sato', '1985-05-22', 'TR4901812', '{"visa":{"nationality":"Japan","visaCategory":"Business","visaSubtype":"e-business","purpose":"Business meetings","proposedArrival":"2026-09-28","arrivalPort":"Delhi International Airport"},"personal":{"surname":"Sato","givenNames":"Kenji","gender":"Male","dob":"1985-05-22","birthCity":"Osaka","birthCountry":"Japan","citizenship":"Japan","religion":"Not stated","identificationMarks":"None","education":"University"},"passport":{"passportNumber":"TR4901812","passportType":"Ordinary","issuingCountry":"Japan","placeOfIssue":"Osaka","issueDate":"2018-01-12","expiryDate":"2028-01-11"},"contact":{"address1":"3-4 Namba","city":"Osaka","state":"Osaka","postalCode":"542-0076","country":"Japan","email":"kenji.sato@example.test","mobile":"+81 6 5555 0100"},"family":{"fatherName":"Hiroshi Sato","fatherNationality":"Japan","motherName":"Yuki Sato","motherNationality":"Japan","maritalStatus":"Married"},"employment":{"occupation":"Engineer","employer":"Sato Robotics","designation":"Project Lead","employerAddress":"3-4 Namba, Osaka","employerPhone":"+81 6 5555 0101","industry":"Technology"},"travel":{"expectedArrival":"2026-09-28","expectedDeparture":"2026-10-06","arrivalPort":"Delhi International Airport","places":"Delhi and Gurugram","accommodationName":"Civic Square Hotel","accommodationAddress":"Connaught Place, New Delhi","indiaReference":"Arjun Rao","indiaReferencePhone":"+91 11 5555 0101","homeReferenceName":"Yuki Sato","homeReferenceRelationship":"Spouse","homeReferencePhone":"+81 6 5555 0102","homeReferenceAddress":"3-4 Namba, Osaka"},"background":{"visaRefusal":"No","deportation":"No","conviction":"No","immigrationViolation":"No","restrictedTravel":"No","declaration":true}}', 11, '2026-08-19T08:00:00.000Z', '2026-08-27T16:10:00.000Z', '2026-08-24T10:00:00.000Z', NULL),
  (5, 'IND-EV-26-DEMO05', 'GRANTED', 'amelia.wilson@example.test', 'Australia', 'e-tourist', '2026-09-12', 'Amelia Wilson', '1990-07-10', 'N8406713', '{"visa":{"nationality":"Australia","visaCategory":"Tourism","visaSubtype":"e-tourist","purpose":"Holiday","proposedArrival":"2026-09-12","arrivalPort":"Goa International Airport"},"personal":{"surname":"Wilson","givenNames":"Amelia","gender":"Female","dob":"1990-07-10","birthCity":"Melbourne","birthCountry":"Australia","citizenship":"Australia","religion":"Not stated","identificationMarks":"None","education":"University"},"passport":{"passportNumber":"N8406713","passportType":"Ordinary","issuingCountry":"Australia","placeOfIssue":"Melbourne","issueDate":"2021-03-02","expiryDate":"2031-03-01"},"contact":{"address1":"21 Swanston Street","city":"Melbourne","state":"Victoria","postalCode":"3000","country":"Australia","email":"amelia.wilson@example.test","mobile":"+61 3 5555 0100"},"family":{"fatherName":"Thomas Wilson","fatherNationality":"Australia","motherName":"Grace Wilson","motherNationality":"Australia","maritalStatus":"Single"},"employment":{"occupation":"Architect","employer":"Wilson Studio","designation":"Architect","employerAddress":"21 Swanston Street, Melbourne","employerPhone":"+61 3 5555 0101","industry":"Design"},"travel":{"expectedArrival":"2026-09-12","expectedDeparture":"2026-09-23","arrivalPort":"Goa International Airport","places":"Goa and Bengaluru","accommodationName":"Palm Courtyard","accommodationAddress":"Panjim, Goa","indiaReference":"Neha Shah","indiaReferencePhone":"+91 832 555 0101","homeReferenceName":"Grace Wilson","homeReferenceRelationship":"Mother","homeReferencePhone":"+61 3 5555 0102","homeReferenceAddress":"21 Swanston Street, Melbourne"},"background":{"visaRefusal":"No","deportation":"No","conviction":"No","immigrationViolation":"No","restrictedTravel":"No","declaration":true}}', 13, '2026-08-10T08:00:00.000Z', '2026-08-22T14:00:00.000Z', '2026-08-15T14:00:00.000Z', NULL),
  (6, 'IND-EV-26-DEMO06', 'REJECTED', 'omar.almansoori@example.test', 'United Arab Emirates', 'e-conference', '2026-09-05', 'Omar Al Mansoori', '1983-12-04', 'A7843021', '{"visa":{"nationality":"United Arab Emirates","visaCategory":"Events","visaSubtype":"e-conference","purpose":"Conference","proposedArrival":"2026-09-05","arrivalPort":"Mumbai International Airport"},"personal":{"surname":"Al Mansoori","givenNames":"Omar","gender":"Male","dob":"1983-12-04","birthCity":"Dubai","birthCountry":"United Arab Emirates","citizenship":"United Arab Emirates","religion":"Not stated","identificationMarks":"None","education":"University"},"passport":{"passportNumber":"A7843021","passportType":"Ordinary","issuingCountry":"United Arab Emirates","placeOfIssue":"Dubai","issueDate":"2017-09-10","expiryDate":"2027-09-09"},"contact":{"address1":"45 Al Wasl Road","city":"Dubai","state":"Dubai","postalCode":"00000","country":"United Arab Emirates","email":"omar.almansoori@example.test","mobile":"+971 4 555 0100"},"family":{"fatherName":"Ahmed Al Mansoori","fatherNationality":"United Arab Emirates","motherName":"Fatima Al Mansoori","motherNationality":"United Arab Emirates","maritalStatus":"Married"},"employment":{"occupation":"Consultant","employer":"Gulf Events LLC","designation":"Director","employerAddress":"45 Al Wasl Road, Dubai","employerPhone":"+971 4 555 0101","industry":"Events"},"travel":{"expectedArrival":"2026-09-05","expectedDeparture":"2026-09-10","arrivalPort":"Mumbai International Airport","places":"Mumbai","accommodationName":"Harbour View Hotel","accommodationAddress":"Colaba, Mumbai","indiaReference":"Priya Menon","indiaReferencePhone":"+91 22 5555 0101","homeReferenceName":"Fatima Al Mansoori","homeReferenceRelationship":"Mother","homeReferencePhone":"+971 4 555 0102","homeReferenceAddress":"45 Al Wasl Road, Dubai"},"background":{"visaRefusal":"No","deportation":"No","conviction":"Yes","immigrationViolation":"No","restrictedTravel":"No","declaration":true}}', 9, '2026-08-05T08:00:00.000Z', '2026-08-21T10:30:00.000Z', '2026-08-12T13:00:00.000Z', 'Background information did not meet the mock review criteria.');

INSERT INTO application_sections (application_id, section, data_json, updated_at) SELECT id, 'visa', json_extract(sections_json, '$.visa'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%';
INSERT INTO application_sections (application_id, section, data_json, updated_at) SELECT id, 'personal', json_extract(sections_json, '$.personal'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%';
INSERT INTO application_sections (application_id, section, data_json, updated_at) SELECT id, 'passport', json_extract(sections_json, '$.passport'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%';
INSERT INTO application_sections (application_id, section, data_json, updated_at) SELECT id, 'contact', json_extract(sections_json, '$.contact'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%' AND json_extract(sections_json, '$.contact') IS NOT NULL;
INSERT INTO application_sections (application_id, section, data_json, updated_at) SELECT id, 'family', json_extract(sections_json, '$.family'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%' AND json_extract(sections_json, '$.family') IS NOT NULL;
INSERT INTO application_sections (application_id, section, data_json, updated_at) SELECT id, 'employment', json_extract(sections_json, '$.employment'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%' AND json_extract(sections_json, '$.employment') IS NOT NULL;
INSERT INTO application_sections (application_id, section, data_json, updated_at) SELECT id, 'travel', json_extract(sections_json, '$.travel'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%' AND json_extract(sections_json, '$.travel') IS NOT NULL;
INSERT INTO application_sections (application_id, section, data_json, updated_at) SELECT id, 'background', json_extract(sections_json, '$.background'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%' AND json_extract(sections_json, '$.background') IS NOT NULL;

INSERT INTO applicants (application_id, surname, given_names, gender, birth_city, birth_country, citizenship, religion, identification_marks, education, data_json, updated_at)
  SELECT id, json_extract(sections_json, '$.personal.surname'), json_extract(sections_json, '$.personal.givenNames'), json_extract(sections_json, '$.personal.gender'), json_extract(sections_json, '$.personal.birthCity'), json_extract(sections_json, '$.personal.birthCountry'), json_extract(sections_json, '$.personal.citizenship'), json_extract(sections_json, '$.personal.religion'), json_extract(sections_json, '$.personal.identificationMarks'), json_extract(sections_json, '$.personal.education'), COALESCE(json_extract(sections_json, '$.personal'), '{}'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%';
INSERT INTO passports (application_id, passport_number, passport_type, issuing_country, place_of_issue, issue_date, expiry_date, data_json, updated_at)
  SELECT id, json_extract(sections_json, '$.passport.passportNumber'), json_extract(sections_json, '$.passport.passportType'), json_extract(sections_json, '$.passport.issuingCountry'), json_extract(sections_json, '$.passport.placeOfIssue'), json_extract(sections_json, '$.passport.issueDate'), json_extract(sections_json, '$.passport.expiryDate'), COALESCE(json_extract(sections_json, '$.passport'), '{}'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%';
INSERT INTO addresses (application_id, data_json, updated_at) SELECT id, json_extract(sections_json, '$.contact'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%' AND json_extract(sections_json, '$.contact') IS NOT NULL;
INSERT INTO family_details (application_id, data_json, updated_at) SELECT id, json_extract(sections_json, '$.family'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%' AND json_extract(sections_json, '$.family') IS NOT NULL;
INSERT INTO employment_details (application_id, data_json, updated_at) SELECT id, json_extract(sections_json, '$.employment'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%' AND json_extract(sections_json, '$.employment') IS NOT NULL;
INSERT INTO travel_details (application_id, data_json, updated_at) SELECT id, json_extract(sections_json, '$.travel'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%' AND json_extract(sections_json, '$.travel') IS NOT NULL;
INSERT INTO visa_details (application_id, data_json, updated_at) SELECT id, json_extract(sections_json, '$.visa'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%';
INSERT INTO background_answers (application_id, data_json, updated_at) SELECT id, json_extract(sections_json, '$.background'), updated_at FROM applications WHERE public_id LIKE 'IND-EV-26-DEMO%' AND json_extract(sections_json, '$.background') IS NOT NULL;

INSERT INTO documents (application_id, document_type, object_key, original_filename, mime_type, size_bytes, status, rejection_reason, uploaded_at, reviewed_at, version) VALUES
  (2, 'photograph', 'applications/2/photograph/demo-daniel.jpg', 'daniel-photo.jpg', 'image/jpeg', 184320, 'ACCEPTED', NULL, '2026-08-26T12:20:00.000Z', '2026-08-27T09:00:00.000Z', 1),
  (2, 'passport', 'applications/2/passport/demo-daniel.pdf', 'daniel-passport.pdf', 'application/pdf', 442100, 'ACCEPTED', NULL, '2026-08-26T12:21:00.000Z', '2026-08-27T09:00:00.000Z', 1),
  (2, 'business-letter', 'applications/2/business-letter/demo-daniel.pdf', 'employer-letter.pdf', 'application/pdf', 311200, 'ACCEPTED', NULL, '2026-08-26T12:22:00.000Z', '2026-08-27T09:00:00.000Z', 1),
  (2, 'invitation-letter', 'applications/2/invitation-letter/demo-daniel.pdf', 'invitation-letter.pdf', 'application/pdf', 278400, 'ACCEPTED', NULL, '2026-08-26T12:23:00.000Z', '2026-08-27T09:00:00.000Z', 1),
  (3, 'photograph', 'applications/3/photograph/demo-sophie.jpg', 'sophie-photo.jpg', 'image/jpeg', 201100, 'ACCEPTED', NULL, '2026-08-25T10:00:00.000Z', '2026-08-26T09:00:00.000Z', 1),
  (3, 'passport', 'applications/3/passport/demo-sophie.pdf', 'sophie-passport.pdf', 'application/pdf', 491000, 'ACCEPTED', NULL, '2026-08-25T10:01:00.000Z', '2026-08-26T09:00:00.000Z', 1),
  (4, 'photograph', 'applications/4/photograph/demo-kenji.jpg', 'kenji-photo.jpg', 'image/jpeg', 198400, 'ACCEPTED', NULL, '2026-08-24T10:10:00.000Z', '2026-08-26T11:00:00.000Z', 1),
  (4, 'passport', 'applications/4/passport/demo-kenji.pdf', 'kenji-passport.pdf', 'application/pdf', 390200, 'REUPLOAD_REQUIRED', 'The lower edge of the passport bio page is cropped.', '2026-08-24T10:11:00.000Z', '2026-08-27T16:00:00.000Z', 1),
  (4, 'business-letter', 'applications/4/business-letter/demo-kenji.pdf', 'employer-letter.pdf', 'application/pdf', 299200, 'ACCEPTED', NULL, '2026-08-24T10:12:00.000Z', '2026-08-26T11:00:00.000Z', 1),
  (4, 'invitation-letter', 'applications/4/invitation-letter/demo-kenji.pdf', 'invitation-letter.pdf', 'application/pdf', 280200, 'ACCEPTED', NULL, '2026-08-24T10:13:00.000Z', '2026-08-26T11:00:00.000Z', 1),
  (5, 'photograph', 'applications/5/photograph/demo-amelia.jpg', 'amelia-photo.jpg', 'image/jpeg', 195100, 'ACCEPTED', NULL, '2026-08-15T14:10:00.000Z', '2026-08-18T10:00:00.000Z', 1),
  (5, 'passport', 'applications/5/passport/demo-amelia.pdf', 'amelia-passport.pdf', 'application/pdf', 428200, 'ACCEPTED', NULL, '2026-08-15T14:11:00.000Z', '2026-08-18T10:00:00.000Z', 1),
  (6, 'photograph', 'applications/6/photograph/demo-omar.jpg', 'omar-photo.jpg', 'image/jpeg', 205400, 'ACCEPTED', NULL, '2026-08-12T13:10:00.000Z', '2026-08-15T10:00:00.000Z', 1),
  (6, 'passport', 'applications/6/passport/demo-omar.pdf', 'omar-passport.pdf', 'application/pdf', 436000, 'ACCEPTED', NULL, '2026-08-12T13:11:00.000Z', '2026-08-15T10:00:00.000Z', 1),
  (6, 'conference-invitation', 'applications/6/conference-invitation/demo-omar.pdf', 'conference-invitation.pdf', 'application/pdf', 305000, 'ACCEPTED', NULL, '2026-08-12T13:12:00.000Z', '2026-08-15T10:00:00.000Z', 1);

INSERT INTO payments (application_id, amount, currency, provider, status, transaction_reference, created_at, updated_at) VALUES
  (2, 83, 'USD', 'Demo payment', 'UNPAID', NULL, '2026-08-28T15:20:00.000Z', '2026-08-28T15:20:00.000Z'),
  (3, 43, 'USD', 'Demo payment', 'SUCCESS', 'DEMO-DEMO03-7A91C2', '2026-08-26T12:05:00.000Z', '2026-08-26T12:06:00.000Z'),
  (4, 51, 'USD', 'Demo payment', 'SUCCESS', 'DEMO-DEMO04-2F71B8', '2026-08-24T10:00:00.000Z', '2026-08-24T10:02:00.000Z'),
  (5, 43, 'USD', 'Demo payment', 'SUCCESS', 'DEMO-DEMO05-6C41D0', '2026-08-15T13:50:00.000Z', '2026-08-15T13:52:00.000Z'),
  (6, 63, 'USD', 'Demo payment', 'SUCCESS', 'DEMO-DEMO06-5D21AF', '2026-08-12T12:50:00.000Z', '2026-08-12T12:52:00.000Z');

INSERT INTO notifications (application_id, type, title, message, created_at) VALUES
  (2, 'PAYMENT_PENDING', 'Payment is still due', 'Complete the demo payment to send your application for review.', '2026-08-28T15:20:00.000Z'),
  (3, 'UNDER_REVIEW', 'Application under review', 'Your payment and documents were received. A visa officer is reviewing the application.', '2026-08-26T12:06:00.000Z'),
  (4, 'DOCUMENT_REUPLOAD_REQUIRED', 'Replace your passport scan', 'The lower edge of the passport bio page is cropped. Upload a clearer scan.', '2026-08-27T16:00:00.000Z'),
  (5, 'VISA_GRANTED', 'Your e-Visa has been granted', 'Your ETA is ready to view and print.', '2026-08-22T14:00:00.000Z'),
  (6, 'VISA_REJECTED', 'Application decision', 'A decision has been recorded for your application.', '2026-08-21T10:30:00.000Z');

INSERT INTO application_events (application_id, type, title, description, actor, created_at) VALUES
  (1, 'APPLICATION_CREATED', 'Application created', 'Your draft application was created.', 'applicant', '2026-08-28T08:10:00.000Z'),
  (2, 'APPLICATION_SUBMITTED', 'Application submitted', 'Your application is ready for payment.', 'applicant', '2026-08-28T15:20:00.000Z'),
  (3, 'PAYMENT_RECEIVED', 'Payment received', 'Your demo payment was received.', 'applicant', '2026-08-26T12:06:00.000Z'),
  (3, 'UNDER_REVIEW', 'Application entered review', 'A visa officer is reviewing your application.', 'system', '2026-08-26T12:10:00.000Z'),
  (4, 'DOCUMENT_REUPLOAD_REQUESTED', 'Document replacement requested', 'The passport bio page needs to be replaced: the lower edge is cropped.', 'Visa Review Officer', '2026-08-27T16:00:00.000Z'),
  (5, 'VISA_GRANTED', 'Visa granted', 'Your e-Visa was granted and the ETA is ready.', 'Visa Review Officer', '2026-08-22T14:00:00.000Z'),
  (6, 'VISA_REJECTED', 'Application decision recorded', 'Background information did not meet the mock review criteria.', 'Visa Review Officer', '2026-08-21T10:30:00.000Z');

INSERT INTO etas (application_id, eta_number, granted_at, valid_from, valid_until, entries, conditions) VALUES
  (5, 'ETA-DEMO05-7H4K2P', '2026-08-22', '2026-09-12', '2027-09-11', 'Double', 'Carry your ETA and passport when travelling.');
