import { useEffect, useState } from 'react'
import { ArrowLeft, Printer } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError } from '../lib/api'
import type { Application } from '../lib/types'
import { PageError, PageLoading } from '../components/application/PageState'
import { Notice, formatDate } from '../components/forms/FormPrimitives'

export default function Eta() {
  const { applicationId } = useParams<{ applicationId: string }>()
  const navigate = useNavigate()
  const [application, setApplication] = useState<Application | null>(null)
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)
  useEffect(() => { if (!applicationId) return; void api.getApplication(applicationId).then(setApplication).catch((requestError) => setError(requestError instanceof ApiError ? requestError.message : "We couldn't load this ETA.")).finally(() => setLoading(false)) }, [applicationId])
  if (loading) return <PageLoading label="Preparing your electronic travel authorisation…" />
  if (error || !application) return <PageError message={error || 'This application could not be found.'} retry={() => window.location.reload()} />
  if (application.status !== 'GRANTED') return <main className="shell py-12 sm:py-20"><div className="max-w-xl"><Link className="link inline-flex items-center gap-2 text-sm" to={`/application/${application.publicId}`}><ArrowLeft size={15} aria-hidden="true" />Back to application</Link><h1 className="display mt-10 text-5xl">The ETA is not ready yet.</h1><p className="mt-5 text-base leading-7 text-stone">This application has not reached a granted decision. Return to the application workspace for the latest status.</p><button type="button" className="btn btn-primary mt-8" onClick={() => navigate(`/application/${application.publicId}`)}>View application</button></div></main>
  const eta = application.eta
  return <main className="shell py-10 sm:py-16"><div className="no-print mb-8 flex flex-wrap items-center justify-between gap-4"><Link className="link inline-flex items-center gap-2 text-sm" to={`/application/${application.publicId}`}><ArrowLeft size={15} aria-hidden="true" />Back to application</Link><button type="button" className="btn btn-primary gap-2" onClick={() => window.print()}><Printer size={15} aria-hidden="true" />Print ETA</button></div><article className="mx-auto max-w-4xl border-2 border-[var(--ink)] bg-white"><header className="flex flex-wrap items-start justify-between gap-6 border-b-2 border-[var(--ink)] bg-[var(--espresso)] p-6 text-white sm:p-8"><div><p className="eyebrow text-[#d5cec6]">Government of India · Prototype</p><h1 className="display mt-3 text-4xl">Electronic Travel Authorisation</h1></div><div className="text-left sm:text-right"><p className="eyebrow text-[#d5cec6]">Decision</p><p className="mt-2 text-lg font-medium tracking-wide">GRANTED</p></div></header><div className="p-6 sm:p-10"><div className="grid gap-x-10 gap-y-0 md:grid-cols-2"><EtaRow label="ETA number" value={eta?.etaNumber || 'DEMO-ETA-PENDING'} strong /><EtaRow label="Application ID" value={application.publicId} strong /><EtaRow label="Applicant" value={application.applicantName || 'Applicant'} /><EtaRow label="Passport number" value={application.passportNumber || '—'} /><EtaRow label="Nationality" value={application.nationality || '—'} /><EtaRow label="Visa type" value={application.visaTypeName || application.visaType} /><EtaRow label="Date granted" value={formatDate(eta?.grantedAt || application.updatedAt)} /><EtaRow label="Expected arrival" value={formatDate(application.proposedArrival)} /><EtaRow label="Valid from" value={formatDate(eta?.validFrom)} /><EtaRow label="Valid until" value={formatDate(eta?.validUntil)} /><EtaRow label="Entries" value={eta?.entries || 'As stated in decision'} /><EtaRow label="Conditions" value={eta?.conditions || 'Subject to prototype terms'} /></div><div className="mt-10"><Notice title="Prototype document. Not valid for travel." tone="action">This page is a fictional demonstration of the redesigned service and does not grant permission to enter India.</Notice></div></div><footer className="border-t border-[var(--hairline)] px-6 py-4 text-xs text-stone sm:px-10"><p>Generated by the Indian e-Visa redesign prototype · Keep your application reference with this document.</p></footer></article></main>
}

function EtaRow({ label, value, strong }: { label: string; value?: string; strong?: boolean }) { return <div className="border-b border-[var(--hairline)] py-4"><dt className="text-xs uppercase tracking-[.08em] text-stone">{label}</dt><dd className={`m-0 mt-2 break-words text-sm ${strong ? 'font-medium tracking-wide' : ''}`}>{value || '—'}</dd></div> }

